In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [20]:
df=pd.read_csv("C:\\Users\\apadh\\OneDrive\\Desktop\\ml_journey\\feature_engineering\\student_data.csv.xls")

In [21]:
df.head()

StudentID  Age  Gender  Ethnicity  ParentalEducation  StudyTimeWeekly  \
0       1001   17       1          1                  3               16   
1       1002   18       1          2                  0               17   
2       1003   15       1          0                  1               13   
3       1004   17       1          0                  3                6   
4       1005   17       0          1                  2                6   

   Absences  Tutoring  ParentalSupport  Extracurricular  Sports  Music  \
0        13         0                2                0       0      0   
1        28         0                2                1       1      1   
2        18         1                4                0       0      0   
3         4         0                3                1       0      0   
4        20         0                4                0       0      0   

   Volunteering       GPA  GradeClass  
0             0  3.158425           1  
1             0  2.794655           2  
2             1  3.774847           0  
3             0  3.040574           1  
4             0  3.382310           1

In [22]:
df.tail()

StudentID  Age  Gender  Ethnicity  ParentalEducation  StudyTimeWeekly  \
4995       5996   15       0          3                  2               12   
4996       5997   16       0          1                  2                1   
4997       5998   17       1          1                  3               18   
4998       5999   16       0          2                  2               15   
4999       6000   18       1          2                  4                4   

      Absences  Tutoring  ParentalSupport  Extracurricular  Sports  Music  \
4995        22         0                2                0       1      1   
4996         2         0                2                0       1      0   
4997        18         1                0                1       0      0   
4998         0         0                2                1       1      1   
4999        23         0                0                1       0      0   

      Volunteering       GPA  GradeClass  
4995             0  4.000000           0  
4996             0  2.533415           2  
4997             1  4.000000           0  
4998             0  4.000000           0  
4999             1  2.000000           3

In [23]:
df.isnull().sum()

StudentID            0
Age                  0
Gender               0
Ethnicity            0
ParentalEducation    0
StudyTimeWeekly      0
Absences             0
Tutoring             0
ParentalSupport      0
Extracurricular      0
Sports               0
Music                0
Volunteering         0
GPA                  0
GradeClass           0
dtype: int64

In [24]:
df.shape

(5000, 15)

In [25]:
df.columns

Index(['StudentID', 'Age', 'Gender', 'Ethnicity', 'ParentalEducation',
       'StudyTimeWeekly', 'Absences', 'Tutoring', 'ParentalSupport',
       'Extracurricular', 'Sports', 'Music', 'Volunteering', 'GPA',
       'GradeClass'],
      dtype='object')

In [26]:
df["GPA"]=df["GPA"].astype("int")

In [27]:
df.dtypes

StudentID            int64
Age                  int64
Gender               int64
Ethnicity            int64
ParentalEducation    int64
StudyTimeWeekly      int64
Absences             int64
Tutoring             int64
ParentalSupport      int64
Extracurricular      int64
Sports               int64
Music                int64
Volunteering         int64
GPA                  int64
GradeClass           int64
dtype: object

In [28]:
df.drop(columns="StudentID",inplace=True)

In [29]:
df.head()

Age  Gender  Ethnicity  ParentalEducation  StudyTimeWeekly  Absences  \
0   17       1          1                  3               16        13   
1   18       1          2                  0               17        28   
2   15       1          0                  1               13        18   
3   17       1          0                  3                6         4   
4   17       0          1                  2                6        20   

   Tutoring  ParentalSupport  Extracurricular  Sports  Music  Volunteering  \
0         0                2                0       0      0             0   
1         0                2                1       1      1             0   
2         1                4                0       0      0             1   
3         0                3                1       0      0             0   
4         0                4                0       0      0             0   

   GPA  GradeClass  
0    3           1  
1    2           2  
2    3           0  
3    3           1  
4    3           1

In [30]:
X=df.iloc[:,:-1]
Y=df.iloc[:,-1]

In [31]:
X

Age  Gender  Ethnicity  ParentalEducation  StudyTimeWeekly  Absences  \
0      17       1          1                  3               16        13   
1      18       1          2                  0               17        28   
2      15       1          0                  1               13        18   
3      17       1          0                  3                6         4   
4      17       0          1                  2                6        20   
...   ...     ...        ...                ...              ...       ...   
4995   15       0          3                  2               12        22   
4996   16       0          1                  2                1         2   
4997   17       1          1                  3               18        18   
4998   16       0          2                  2               15         0   
4999   18       1          2                  4                4        23   

      Tutoring  ParentalSupport  Extracurricular  Sports  Music  Volunteering  \
0            0                2                0       0      0             0   
1            0                2                1       1      1             0   
2            1                4                0       0      0             1   
3            0                3                1       0      0             0   
4            0                4                0       0      0             0   
...        ...              ...              ...     ...    ...           ...   
4995         0                2                0       1      1             0   
4996         0                2                0       1      0             0   
4997         1                0                1       0      0             1   
4998         0                2                1       1      1             0   
4999         0                0                1       0      0             1   

      GPA  
0       3  
1       2  
2       3  
3       3  
4       3  
...   ...  
4995    4  
4996    2  
4997    4  
4998    4  
4999    2  

[5000 rows x 13 columns]

In [32]:
Y

0       1
1       2
2       0
3       1
4       1
       ..
4995    0
4996    2
4997    0
4998    0
4999    3
Name: GradeClass, Length: 5000, dtype: int64

In [33]:
! pip install scikit-learn


[notice] A new release of pip is available: 24.0 -> 25.3
[notice] To update, run: C:\Users\apadh\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [34]:
from sklearn.preprocessing import MinMaxScaler

In [35]:
scaler=MinMaxScaler()
scaler.fit(X)
Xscale=scaler.fit_transform(X)
Xscale

array([[0.66666667, 1.        , 0.33333333, ..., 0.        , 0.        ,
        0.5       ],
       [1.        , 1.        , 0.66666667, ..., 1.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 0.        , 1.        ,
        0.5       ],
       ...,
       [0.66666667, 1.        , 0.33333333, ..., 0.        , 1.        ,
        1.        ],
       [0.33333333, 0.        , 0.66666667, ..., 1.        , 0.        ,
        1.        ],
       [1.        , 1.        , 0.66666667, ..., 0.        , 1.        ,
        0.        ]], shape=(5000, 13))

In [36]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(Xscale,Y,test_size=0.2)

In [37]:
X_train

array([[0.66666667, 0.        , 0.        , ..., 1.        , 1.        ,
        1.        ],
       [1.        , 0.        , 1.        , ..., 0.        , 0.        ,
        0.        ],
       [1.        , 1.        , 0.        , ..., 1.        , 0.        ,
        0.5       ],
       ...,
       [0.        , 1.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.33333333, 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [1.        , 1.        , 0.        , ..., 0.        , 0.        ,
        0.5       ]], shape=(4000, 13))

In [38]:
X_test

array([[0.33333333, 0.        , 0.        , ..., 0.        , 0.        ,
        0.5       ],
       [0.66666667, 0.        , 0.33333333, ..., 1.        , 0.        ,
        0.5       ],
       [0.        , 0.        , 0.66666667, ..., 1.        , 0.        ,
        0.5       ],
       ...,
       [0.        , 1.        , 0.        , ..., 0.        , 0.        ,
        0.5       ],
       [0.66666667, 1.        , 0.        , ..., 0.        , 0.        ,
        1.        ],
       [0.66666667, 1.        , 0.        , ..., 0.        , 0.        ,
        1.        ]], shape=(1000, 13))